# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a00559e5981860134810f25bd9d54bd6ed0906e9cb46d90c243adb471dc464057def85c969d7822eed7f96013bb8aa6d936e2839d81bb278d4128d9fbfab4d0a

test:
  secret_key_base: 7ede40728e28c84460c5db40192796639ef66e1936b1800cc1f1789764eda53caee2ffb2534344fff34fc606b16c4e41b429053f98dd3156f2f9d1c5e50299b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
